name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure Cmake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Build
      run: cmake --build .
    - name: Test
      run: ctest --verbose
