name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure Cmake
      run: CC=clang cmake -B build
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build/tests --verbose
