name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Clang
      run: |
        apt-get update
        apt-get upgrade
        apt-get install -y clang
    - name: Configure Cmake
      run: |
        mkdir build
        cd build
        CC=clang cmake ..
    - name: Build
      run: cmake --build build
    - name: Test
      run: |
        cd build
        ctest --verbose
